version: "3"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - db-net
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

volumes:
  db:

networks:
  db-net:
    external: true
