- become: yes
  hosts: all
  name: install and ban google
  tasks:
    - name: install docker using script
      shell: curl https://get.docker.com | bash
    
    - name: install pip
      apt:
        name: python3-pip
    - name: install python module
      pip:
        name: 
          - docker>=5.0.0
          - jsondiff

    - name: install iptables-persistent
      apt:
        name: iptables-persistent

    - name: ban 8.8.8.8
      iptables:
        chain: DOCKER-USER
        comment: fixes_long_svc_startup
        destination: 8.8.8.8
        jump: REJECT

    - name: save rule
      community.general.iptables_state:
        state: saved
        path: /etc/iptables/rules.v4

