student_email: novikovprojects@gmail.com
postgres_cluster:
  hosts:
  - address: postgres
    port: 5432
  user: postgres
  password: postgres
  db_name: postgres
  ssl_mode: disable
  use_closest_node: false
